[package]
name = "hyperlane-validator-blueprint"
version = "0.1.0"
edition = "2021"
description = "A Tangle Blueprint (AVS) for deploying Hyperlane validators"
authors = ["Serial <69764315+Serial-ATA@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
homepage = "https://tangle.tools"
repository = "https://github.com/tangle-network/hyperlane-validator-blueprint"
readme = "README.md"
categories = ["cryptography", "cryptography::cryptocurrencies"]
keywords = ["tangle", "blueprint", "avs"]
rust-version = "1.81"

[dependencies]
tracing = "0.1"
color-eyre = "0.6"
hex = "0.4.3"
tokio = "1.43.0"
reqwest = "0.12.8"

[dependencies.gadget-sdk]
git = "https://github.com/tangle-network/gadget.git"
#path = "../gadget/sdk"
default-features = false
features = ["getrandom"]

[build-dependencies]
blueprint-metadata = "0.2.1"

[dev-dependencies]
blueprint-test-utils = { git = "https://github.com/tangle-network/gadget.git" }
#blueprint-test-utils = { path = "../gadget/blueprint-test-utils" }
tempfile = "3.10.0"
testcontainers = "0.23.1"
tracing-subscriber = "0.3.18"

[features]
default = ["std"]
std = ["gadget-sdk/std"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "hyperlane-relayer-blueprint"
path = "src/main.rs"

[package.metadata.blueprint]
manager = { Evm = "HyperlaneRelayerBlueprint" }
