[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# Build only the required packages, and individually
precise-builds = true
# Generate and dist a source tarball
source-tarball = false
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
github-build-setup = "build-setup.yml"
# Whether to enable GitHub Attestations
github-attestations = true
members = ["cargo:/hyperlane-validator-bin"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-musl"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Which actions to run on pull requests
pr-run-mode = "plan"
# The installers to generate for each app
installers = []

[dist.github-custom-runners]
global = "ubuntu-latest"
x86_64-unknown-linux-musl = "ubuntu-latest"
